import { cached } from "./wrapper"
import { getPayloadClient } from "@/db/client"
import type { Media } from "@/payload-types"

export interface CompanySettingsData {
  id: string
  companyName: string
  companyLogo?: string | Media | null
  partner?: {
    isActive?: boolean | null
    name?: string | null
    websiteUrl?: string | null
    logo?: string | Media | null
    badgeText?: string | null
  } | null
  contactEmail?: string | null
  notificationEmail?: string | null
  contactPhone?: string | null
  contactOffice?: string | null
  socialMedia?: {
    facebook?: string | null
    instagram?: string | null
    youtube?: string | null
  } | null
  updatedAt?: string | null
  createdAt?: string | null
}

/**
 * Retrieves the CompanySettings global via serialization-safe on-demand cache.
 * 
 * Duration: Infinite (revalidate: false) — invalidated strictly on-demand when 'company-settings' tag is triggered.
 * Tags: ['company-settings']
 */
export const getCachedCompanySettings = async (): Promise<CompanySettingsData> => {
  const cacheKey = `company-settings-global-v2`

  const rawDoc = await cached(
    async () => {
      const payload = await getPayloadClient()
      const settings = await payload.findGlobal({
        // Use 'as never' temporarily until payload-types.ts is re-generated by the user
        slug: 'company-settings' as never,
        depth: 1,
      })
      return settings
    },
    [cacheKey],
    {
      revalidate: false,
      tags: ["company-settings"],
    }
  )()

  return rawDoc as unknown as CompanySettingsData
}


