import { unstable_cache } from "next/cache"
import { getPayloadClient } from "@/db/client"
import type { Media } from "@/payload-types"

export interface CompanySettingsData {
  id: string
  companyName: string
  companyLogo?: string | Media | null
  partner?: {
    isActive?: boolean | null
    name?: string | null
    websiteUrl?: string | null
    logo?: string | Media | null
    badgeText?: string | null
  }
  contactEmail?: string | null
  contactPhone?: string | null
  contactOffice?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}

/**
 * Retrieves the CompanySettings global via serialization-safe cache.
 * 
 * Duration: 1 Day (86400s) — safety net only
 * Tags: 'company-settings'
 */
export const getCachedCompanySettings = async (): Promise<CompanySettingsData> => {
  const cacheKey = `company-settings-global-v2`

  const rawDoc = await unstable_cache(
    async () => {
      console.log(`⚡ [CACHE MISS]: company-settings-global-v2 (Querying PostgreSQL Remote DB...)`)
      const payload = await getPayloadClient()
      const settings = await payload.findGlobal({
        // Use 'as never' temporarily until payload-types.ts is re-generated by the user
        slug: 'company-settings' as never,
        depth: 1,
      })
      return settings
    },
    [cacheKey],
    {
      revalidate: 86400,
      tags: ["company-settings"],
    }
  )()

  return rawDoc as unknown as CompanySettingsData
}
