/**
 * Centralized Media Configuration
 *
 * Single source of truth for all media-related constants.
 * Shared between client-side validation, server-side hooks, and collection config.
 *
 * IMPORTANT: This module must remain isomorphic (no Node.js APIs)
 * so it can be imported in both server and browser contexts.
 */

// ---------------------------------------------------------------------------
// File Size Limits
// ---------------------------------------------------------------------------

/** Maximum file size in bytes for image uploads (6 MB) */
export const MAX_IMAGE_FILE_SIZE_BYTES = 6 * 1024 * 1024

/** Category-specific photo limits */
export type PropertyCategorySlug = 'residential' | 'commercial' | 'hospitality' | 'land'

export const MAX_PHOTOS_BY_CATEGORY: Record<PropertyCategorySlug, number> = {
  hospitality: 30,
  commercial: 30,
  residential: 15,
  land: 15,
}

export const DEFAULT_MAX_PHOTOS_PER_SELLER_REQUEST = 15

/**
 * Returns the maximum number of photos allowed for a given property category.
 */
export function getMaxPhotosForCategory(category?: string | null): number {
  if (!category) return DEFAULT_MAX_PHOTOS_PER_SELLER_REQUEST
  return MAX_PHOTOS_BY_CATEGORY[category as PropertyCategorySlug] || DEFAULT_MAX_PHOTOS_PER_SELLER_REQUEST
}

/** Fallback maximum number of photos allowed per seller request */
export const MAX_PHOTOS_PER_SELLER_REQUEST = 30

/** Maximum concurrent image processing tasks during seller request uploads to preserve CPU/RAM */
export const UPLOAD_CONCURRENCY = 2

/** Maximum file size in bytes for document uploads (20 MB) — future use */
export const MAX_DOCUMENT_FILE_SIZE_BYTES = 20 * 1024 * 1024

// ---------------------------------------------------------------------------
// Dimension Limits
// ---------------------------------------------------------------------------

/** Maximum width or height in pixels for uploaded images */
export const MAX_IMAGE_DIMENSION_PX = 8192

/** Minimum width or height in pixels for uploaded images */
export const MIN_IMAGE_DIMENSION_PX = 50

// ---------------------------------------------------------------------------
// Allowed MIME Types
// ---------------------------------------------------------------------------

/**
 * MIME types accepted for image uploads.
 * The Payload `mimeTypes` filter uses glob patterns, but for programmatic
 * validation we list concrete types.
 */
export const ALLOWED_IMAGE_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/svg+xml',
  'image/avif',
] as const

/** Payload-compatible glob pattern for upload config */
export const PAYLOAD_MIME_TYPES_GLOB = ['image/*'] as const

// ---------------------------------------------------------------------------
// Image Processing
// ---------------------------------------------------------------------------

/**
 * Output format & quality for processed images.
 * Quality 83 is the recommended sweet spot for WebP (visual quality vs. size).
 */
export const IMAGE_FORMAT_OPTIONS = {
  format: 'webp' as const,
  options: {
    quality: 83,
  },
}

/**
 * Maximum dimensions for the *original* stored image.
 * Images larger than this will be resized down on upload.
 */
export const IMAGE_RESIZE_OPTIONS = {
  width: 1920,
  height: 1080,
  fit: 'inside' as const,
  withoutEnlargement: true,
}

/**
 * Named image sizes generated by Payload on upload.
 * Each entry produces a resized variant stored alongside the original.
 *
 * These are actively used in production:
 * - thumbnail: map popups, gallery strip
 * - card: listing cards, search results, dashboards (7+ files)
 * - hero: main property hero image
 */
export const IMAGE_SIZES = [
  {
    name: 'thumbnail' as const,
    width: 400,
    height: 300,
    crop: 'center' as const,
  },
  {
    name: 'card' as const,
    width: 800,
    height: 600,
    crop: 'center' as const,
  },
  {
    name: 'hero' as const,
    width: 1600,
    height: 900,
    crop: 'center' as const,
  },
] as const

// ---------------------------------------------------------------------------
// Human-Readable Labels (for error messages / UI)
// ---------------------------------------------------------------------------

/**
 * Formats a byte value into a human-readable string (e.g., "10 MB").
 */
export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
