/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    investors: InvestorAuthOperations;
    sellers: SellerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'media-folders': MediaFolder;
    locations: Location;
    properties: Property;
    features: Feature;
    investors: Investor;
    sellers: Seller;
    'verification-codes': VerificationCode;
    'property-views': PropertyView;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    'contact-messages': ContactMessage;
    newsletters: Newsletter;
    'seller-requests': SellerRequest;
    'property-types': PropertyType;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-folders': MediaFoldersSelect<false> | MediaFoldersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    investors: InvestorsSelect<false> | InvestorsSelect<true>;
    sellers: SellersSelect<false> | SellersSelect<true>;
    'verification-codes': VerificationCodesSelect<false> | VerificationCodesSelect<true>;
    'property-views': PropertyViewsSelect<false> | PropertyViewsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'seller-requests': SellerRequestsSelect<false> | SellerRequestsSelect<true>;
    'property-types': PropertyTypesSelect<false> | PropertyTypesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Investor | Seller;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface InvestorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SellerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin users and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The visual name of the file shown in the Media Library UI.
   */
  displayName?: string | null;
  /**
   * The physical storage identifier for this media file (immutable after creation).
   */
  storageKey?: string | null;
  /**
   * Descriptive alternative text for accessibility and SEO. Describe what the image shows.
   */
  alt: string;
  /**
   * Assign this media item to a virtual folder for organization.
   */
  folder?: (number | null) | MediaFolder;
  /**
   * Add tags for easier filtering and search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional descriptive caption for this media item.
   */
  caption?: string | null;
  /**
   * The original filename before Payload processing.
   */
  originalFilename?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-folders".
 */
export interface MediaFolder {
  id: number;
  /**
   * Display name for this folder.
   */
  name: string;
  /**
   * Auto-generated URL-safe identifier.
   */
  slug: string;
  /**
   * Leave empty for a root-level folder.
   */
  parent?: (number | null) | MediaFolder;
  /**
   * Materialized path (e.g., /properties/luxury). Auto-computed from parent chain.
   */
  path: string;
  /**
   * Nesting level (0 = root folder).
   */
  depth: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  formattedLocation?: string | null;
  zip: string;
  /**
   * City of the zip code
   */
  city: string;
  /**
   * State abbreviation of the zip code
   */
  state_abbr: string;
  /**
   * State name of the zip code
   */
  state_name: string;
  /**
   * County of the zip code
   */
  county?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Estimated population of the zip code
   */
  est_population?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: string;
  /**
   * The property owner/seller contact
   */
  seller?: (number | null) | Seller;
  /**
   * Original seller request (if applicable)
   */
  seller_request?: (number | null) | SellerRequest;
  /**
   * Total tracked property views
   */
  views?: number | null;
  title: string;
  description: string;
  /**
   * Select or add the type of this property.
   */
  propertyType?: (number | null) | PropertyType;
  price?: number | null;
  currency: 'EGP' | 'USD' | 'EUR';
  basePriceInUSD?: number | null;
  listingStatus: 'forsale' | 'pending' | 'contract' | 'contingent' | 'sold' | 'offmarket' | 'notforsale';
  /**
   * The physical construction state of the property.
   */
  constructionStatus: 'ready' | 'under_construction' | 'brand_new' | 'off_plan' | 'renovated';
  details?: {
    bedrooms?: number | null;
    bathrooms?: number | null;
    squareMeters?: number | null;
    lotSize?: number | null;
    yearBuilt?: number | null;
    heatingType?: ('central' | 'electric' | 'gas' | 'oil' | 'propane') | null;
  };
  photos?: (number | Media)[] | null;
  /**
   * Paste a Google Maps URL (short/long), coordinates (lat,lng), or search address to auto-fill details.
   */
  mapsUrlInput?: string | null;
  location?: {
    geo?: {
      lat?: number | null;
      lng?: number | null;
    };
    address?: {
      street?: string | null;
      city?: string | null;
      state?: string | null;
      country?: string | null;
      zip?: string | null;
      /**
       * Auto-generated from components above.
       */
      fullAddress?: string | null;
    };
    search?: {
      citySlug?: string | null;
      stateSlug?: string | null;
      normalizedAddress?: string | null;
    };
    meta?: {
      source?: ('manual' | 'google_maps' | 'imported') | null;
      extractedAt?: string | null;
      extractionConfidence?: number | null;
    };
  };
  street?: string | null;
  location_legacy?: (number | null) | Location;
  /**
   * Select the features for this property.
   */
  features?: (number | Feature)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registered sellers/owners with properties listed
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sellers".
 */
export interface Seller {
  id: number;
  full_name: string;
  phone: string;
  company_name?: string | null;
  /**
   * Current verification status of the seller
   */
  verification_status: 'pending' | 'verified' | 'rejected';
  /**
   * Internal notes about this seller (only visible to admins)
   */
  notes?: string | null;
  /**
   * Total number of properties listed on the platform for this seller
   */
  properties_count?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'sellers';
}
/**
 * Incoming property listing requests from sellers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller-requests".
 */
export interface SellerRequest {
  id: number;
  full_name: string;
  email: string;
  phone: string;
  property_type: number | PropertyType;
  property_title: string;
  property_description: string;
  /**
   * City, State, or full address
   */
  property_location: string;
  asking_price?: number | null;
  property_size?: number | null;
  status: 'new' | 'reviewing' | 'approved' | 'rejected' | 'listed';
  /**
   * Auto-linked seller account record
   */
  seller?: (number | null) | Seller;
  /**
   * Internal notes (not visible to seller)
   */
  admin_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types".
 */
export interface PropertyType {
  id: number;
  /**
   * Display name for this property type (e.g., Villa, Hotel, Resort).
   */
  name: string;
  /**
   * URL-friendly identifier (lowercase, e.g., "villa", "elite-real-estate").
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Name of the feature (e.g., "Hardwood Floors", "Swimming Pool")
   */
  name: string;
  category: 'interior' | 'exterior' | 'community' | 'other';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors".
 */
export interface Investor {
  id: number;
  full_name: string;
  company_name?: string | null;
  phone?: string | null;
  /**
   * Linked Google account identifier
   */
  google_id?: string | null;
  /**
   * Profile image from Google account
   */
  profile_image?: string | null;
  /**
   * Current verification status of the investor
   */
  verification_status: 'pending' | 'submitted' | 'verified' | 'rejected';
  /**
   * Upload proof of financial capability (bank statement, investment portfolio, etc.)
   */
  proof_of_funds?: (number | null) | Media;
  /**
   * Internal notes about this investor (only visible to admins)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'investors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes".
 */
export interface VerificationCode {
  id: number;
  email: string;
  /**
   * 6-digit verification code
   */
  code: string;
  user_type: 'investors' | 'sellers';
  expires_at: string;
  /**
   * Has this code been used to verify an account?
   */
  verified?: boolean | null;
  verified_at?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System-generated analytics log of unique property views. This collection is read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-views".
 */
export interface PropertyView {
  id: number;
  /**
   * The property that was viewed
   */
  property: string | Property;
  /**
   * The logged-in investor or seller who viewed the property (optional)
   */
  user?:
    | ({
        relationTo: 'investors';
        value: number | Investor;
      } | null)
    | ({
        relationTo: 'sellers';
        value: number | Seller;
      } | null);
  /**
   * Unique identifier for the visitor (hashed fingerprint)
   */
  visitorId: string;
  /**
   * Session identifier for tracking multiple views in one session
   */
  sessionId?: string | null;
  viewedAt: string;
  /**
   * Browser user agent
   */
  userAgent?: string | null;
  /**
   * Visitor IP address (hashed for privacy)
   */
  ipAddress?: string | null;
  /**
   * Traffic source
   */
  source?: ('direct' | 'search' | 'social' | 'email' | 'referral' | 'other') | null;
  /**
   * Referrer URL
   */
  referrer?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  location?: {
    country?: string | null;
    city?: string | null;
    region?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * URL-friendly version of the category name
   */
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  /**
   * Color for category badges in the UI
   */
  color?: ('blue' | 'green' | 'red' | 'yellow' | 'purple' | 'gray') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  /**
   * Brief summary (150-200 characters recommended)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image for the post (recommended: 1200x630px)
   */
  featuredImage: number | Media;
  author: string;
  category: number | BlogCategory;
  /**
   * Tags for better organization and SEO
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * The date when this post was/will be published
   */
  publishedDate?: string | null;
  /**
   * Display this post prominently on the blog homepage
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Custom SEO title (defaults to post title)
     */
    metaTitle?: string | null;
    /**
     * Custom SEO description (defaults to excerpt)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    metaKeywords?: string | null;
  };
  /**
   * Estimated time to read this post
   */
  readTime?: number | null;
  /**
   * Number of times this post has been viewed
   */
  views?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  inquiryType: 'investor' | 'property-owner' | 'general' | 'partnership' | 'support' | 'other';
  subject: string;
  message: string;
  /**
   * The property this inquiry is about (if applicable)
   */
  property?: (string | null) | Property;
  preferredContact?: ('email' | 'phone' | 'whatsapp') | null;
  buyingTimeline?: ('immediate' | '1_to_3_months' | '3_to_6_months' | '6_plus_months' | 'browsing') | null;
  budgetRange?: {
    min?: number | null;
    max?: number | null;
  };
  status: 'new' | 'in-progress' | 'resolved' | 'archived';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  /**
   * Assign this message to a team member
   */
  assignedTo?: (number | null) | User;
  /**
   * Internal notes for team (not visible to sender)
   */
  notes?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  doubleOptInConfirmed?: boolean | null;
  confirmedAt?: string | null;
  /**
   * Auto-generated double opt-in token
   */
  confirmationToken?: string | null;
  /**
   * Token expires after 24 hours
   */
  confirmationExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  status: 'subscribed' | 'unsubscribed' | 'bounced' | 'complained';
  subscribeDate: string;
  unsubscribeDate?: string | null;
  source?: ('homepage' | 'blog' | 'contact' | 'footer' | 'popup' | 'manual' | 'other') | null;
  /**
   * Types of content the subscriber is interested in
   */
  interests?: ('investment' | 'market-news' | 'listings' | 'blog' | 'trends' | 'events')[] | null;
  preferences?: {
    frequency?: ('daily' | 'weekly' | 'monthly') | null;
    htmlEmails?: boolean | null;
  };
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * Whether subscriber confirmed their email address
   */
  doubleOptIn?: boolean | null;
  confirmationDate?: string | null;
  /**
   * Internal notes about this subscriber
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-folders';
        value: number | MediaFolder;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'properties';
        value: string | Property;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'investors';
        value: number | Investor;
      } | null)
    | ({
        relationTo: 'sellers';
        value: number | Seller;
      } | null)
    | ({
        relationTo: 'verification-codes';
        value: number | VerificationCode;
      } | null)
    | ({
        relationTo: 'property-views';
        value: number | PropertyView;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'seller-requests';
        value: number | SellerRequest;
      } | null)
    | ({
        relationTo: 'property-types';
        value: number | PropertyType;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'investors';
        value: number | Investor;
      }
    | {
        relationTo: 'sellers';
        value: number | Seller;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'investors';
        value: number | Investor;
      }
    | {
        relationTo: 'sellers';
        value: number | Seller;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  displayName?: T;
  storageKey?: T;
  alt?: T;
  folder?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  caption?: T;
  originalFilename?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-folders_select".
 */
export interface MediaFoldersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  path?: T;
  depth?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  formattedLocation?: T;
  zip?: T;
  city?: T;
  state_abbr?: T;
  state_name?: T;
  county?: T;
  latitude?: T;
  longitude?: T;
  est_population?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  id?: T;
  seller?: T;
  seller_request?: T;
  views?: T;
  title?: T;
  description?: T;
  propertyType?: T;
  price?: T;
  currency?: T;
  basePriceInUSD?: T;
  listingStatus?: T;
  constructionStatus?: T;
  details?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        squareMeters?: T;
        lotSize?: T;
        yearBuilt?: T;
        heatingType?: T;
      };
  photos?: T;
  mapsUrlInput?: T;
  location?:
    | T
    | {
        geo?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
        address?:
          | T
          | {
              street?: T;
              city?: T;
              state?: T;
              country?: T;
              zip?: T;
              fullAddress?: T;
            };
        search?:
          | T
          | {
              citySlug?: T;
              stateSlug?: T;
              normalizedAddress?: T;
            };
        meta?:
          | T
          | {
              source?: T;
              extractedAt?: T;
              extractionConfidence?: T;
            };
      };
  street?: T;
  location_legacy?: T;
  features?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors_select".
 */
export interface InvestorsSelect<T extends boolean = true> {
  full_name?: T;
  company_name?: T;
  phone?: T;
  google_id?: T;
  profile_image?: T;
  verification_status?: T;
  proof_of_funds?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sellers_select".
 */
export interface SellersSelect<T extends boolean = true> {
  full_name?: T;
  phone?: T;
  company_name?: T;
  verification_status?: T;
  notes?: T;
  properties_count?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes_select".
 */
export interface VerificationCodesSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  user_type?: T;
  expires_at?: T;
  verified?: T;
  verified_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-views_select".
 */
export interface PropertyViewsSelect<T extends boolean = true> {
  property?: T;
  user?: T;
  visitorId?: T;
  sessionId?: T;
  viewedAt?: T;
  userAgent?: T;
  ipAddress?: T;
  source?: T;
  referrer?: T;
  device?: T;
  location?:
    | T
    | {
        country?: T;
        city?: T;
        region?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedDate?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  readTime?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  inquiryType?: T;
  subject?: T;
  message?: T;
  property?: T;
  preferredContact?: T;
  buyingTimeline?: T;
  budgetRange?:
    | T
    | {
        min?: T;
        max?: T;
      };
  status?: T;
  priority?: T;
  assignedTo?: T;
  notes?: T;
  ipAddress?: T;
  userAgent?: T;
  doubleOptInConfirmed?: T;
  confirmedAt?: T;
  confirmationToken?: T;
  confirmationExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  status?: T;
  subscribeDate?: T;
  unsubscribeDate?: T;
  source?: T;
  interests?: T;
  preferences?:
    | T
    | {
        frequency?: T;
        htmlEmails?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  doubleOptIn?: T;
  confirmationDate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller-requests_select".
 */
export interface SellerRequestsSelect<T extends boolean = true> {
  full_name?: T;
  email?: T;
  phone?: T;
  property_type?: T;
  property_title?: T;
  property_description?: T;
  property_location?: T;
  asking_price?: T;
  property_size?: T;
  status?: T;
  seller?: T;
  admin_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types_select".
 */
export interface PropertyTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}