/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    buyers: BuyerAuthOperations;
    sellers: SellerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'media-folders': MediaFolder;
    locations: Location;
    properties: Property;
    features: Feature;
    buyers: Buyer;
    sellers: Seller;
    'verification-codes': VerificationCode;
    'property-views': PropertyView;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    'contact-messages': ContactMessage;
    'seller-requests': SellerRequest;
    'property-types': PropertyType;
    'listing-statuses': ListingStatus;
    'construction-statuses': ConstructionStatus;
    'property-categories': PropertyCategory;
    'ip-locations': IpLocation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      usedInBlogPosts: 'blog-posts';
      usedInProperties: 'properties';
      usedInBuyers: 'buyers';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-folders': MediaFoldersSelect<false> | MediaFoldersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    buyers: BuyersSelect<false> | BuyersSelect<true>;
    sellers: SellersSelect<false> | SellersSelect<true>;
    'verification-codes': VerificationCodesSelect<false> | VerificationCodesSelect<true>;
    'property-views': PropertyViewsSelect<false> | PropertyViewsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'seller-requests': SellerRequestsSelect<false> | SellerRequestsSelect<true>;
    'property-types': PropertyTypesSelect<false> | PropertyTypesSelect<true>;
    'listing-statuses': ListingStatusesSelect<false> | ListingStatusesSelect<true>;
    'construction-statuses': ConstructionStatusesSelect<false> | ConstructionStatusesSelect<true>;
    'property-categories': PropertyCategoriesSelect<false> | PropertyCategoriesSelect<true>;
    'ip-locations': IpLocationsSelect<false> | IpLocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'company-settings': CompanySetting;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Buyer | Seller;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface BuyerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface SellerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage admin users and permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The visual name of the file shown in the Media Library UI.
   */
  displayName?: string | null;
  /**
   * The physical storage identifier for this media file (immutable after creation).
   */
  storageKey?: string | null;
  /**
   * Descriptive alternative text for accessibility and SEO. Describe what the image shows.
   */
  alt: string;
  /**
   * Assign this media item to a virtual folder for organization.
   */
  folder?: (number | null) | MediaFolder;
  /**
   * Add tags for easier filtering and search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional descriptive caption for this media item.
   */
  caption?: string | null;
  /**
   * Physical storage health status. Auto-managed by the system.
   */
  healthStatus?: ('ready' | 'missing' | 'broken' | 'migrating' | 'deleted') | null;
  /**
   * The original filename before Payload processing.
   */
  originalFilename?: string | null;
  /**
   * Blog posts using this media
   */
  usedInBlogPosts?: {
    docs?: (number | BlogPost)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Properties using this media
   */
  usedInProperties?: {
    docs?: (string | Property)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Buyers using this media
   */
  usedInBuyers?: {
    docs?: (number | Buyer)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-folders".
 */
export interface MediaFolder {
  id: number;
  /**
   * Display name for this folder.
   */
  name: string;
  /**
   * Auto-generated URL-safe identifier.
   */
  slug: string;
  /**
   * Leave empty for a root-level folder.
   */
  parent?: (number | null) | MediaFolder;
  /**
   * Materialized path (e.g., /properties/luxury). Auto-computed from parent chain.
   */
  path: string;
  /**
   * Nesting level (0 = root folder).
   */
  depth: number;
  /**
   * Custom sort order for manual drag-and-drop positioning within siblings.
   */
  sortOrder: number;
  /**
   * Optional color for visual organization.
   */
  color?: ('default' | 'red' | 'orange' | 'yellow' | 'green' | 'blue' | 'purple' | 'pink') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * Brief summary (150-200 characters recommended)
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image for the post (recommended: 1200x630px)
   */
  featuredImage: number | Media;
  author: string;
  category: number | BlogCategory;
  /**
   * Tags for better organization and SEO
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * The date when this post was/will be published
   */
  publishedDate?: string | null;
  /**
   * Display this post prominently on the blog homepage
   */
  featured?: boolean | null;
  seo?: {
    /**
     * Custom SEO title (defaults to post title)
     */
    metaTitle?: string | null;
    /**
     * Custom SEO description (defaults to excerpt)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO
     */
    metaKeywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  /**
   * Brief description of this category
   */
  description?: string | null;
  /**
   * Color for category badges in the UI
   */
  color?: ('blue' | 'green' | 'red' | 'yellow' | 'purple' | 'gray') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: string;
  /**
   * Custom sorting order (lower numbers display first, unassigned default to 99999)
   */
  sortOrder?: number | null;
  /**
   * The property owner/seller contact
   */
  seller?: (number | null) | Seller;
  /**
   * Original seller request (if applicable)
   */
  seller_request?: (number | null) | SellerRequest;
  /**
   * Total tracked property views
   */
  views?: number | null;
  propertyTypeSlug?: string | null;
  title: string;
  /**
   * Select the main category.
   */
  category: 'residential' | 'commercial' | 'hospitality' | 'land';
  /**
   * Select property type.
   */
  propertyType?: (number | null) | PropertyType;
  listingStatus: number | ListingStatus;
  /**
   * Physical construction state.
   */
  constructionStatus?: (number | null) | ConstructionStatus;
  description: string;
  price?: number | null;
  currency: 'EGP' | 'USD' | 'EUR';
  /**
   * Total area in square meters (m²)
   */
  area?: number | null;
  basePriceInUSD?: number | null;
  residential?: {
    bedrooms?: number | null;
    bathrooms?: number | null;
    floor?: number | null;
    floors?: number | null;
    yearBuilt?: number | null;
    heatingType?: ('central' | 'electric' | 'gas' | 'oil' | 'propane') | null;
    villa?: {
      pools?: number | null;
      hasGarden?: boolean | null;
      hasGarage?: boolean | null;
      hasMajlis?: boolean | null;
      hasDriverRoom?: boolean | null;
      hasMaidRoom?: boolean | null;
    };
    apartment?: {
      hasBalcony?: boolean | null;
      hasMaidRoom?: boolean | null;
    };
    chalet?: {
      hasPool?: boolean | null;
      hasGarden?: boolean | null;
      isBeachfront?: boolean | null;
    };
  };
  commercial?: {
    floor?: number | null;
    parkingSpaces?: number | null;
    licenseType?: string | null;
    office?: {
      meetingRooms?: number | null;
      hasReception?: boolean | null;
      internetType?: ('fiber' | 'adsl' | 'none') | null;
      securityLevel?: ('24_7' | 'business_hours' | 'none') | null;
      elevators?: number | null;
    };
    restaurant?: {
      kitchenCount?: number | null;
      hasExhaust?: boolean | null;
      hasGasConnection?: boolean | null;
      outdoorSeatingCapacity?: number | null;
    };
    warehouse?: {
      loadingDocks?: number | null;
      /**
       * Unit: m
       */
      ceilingHeight?: number | null;
      hasTruckAccess?: boolean | null;
      fireSystem?: ('sprinkler' | 'extinguisher' | 'full' | 'none') | null;
    };
    factory?: {
      /**
       * Unit: kW
       */
      powerCapacityKW?: number | null;
      hazardZone?: ('none' | 'low' | 'medium' | 'high') | null;
      industrialLicense?: string | null;
    };
    retail?: {
      /**
       * Unit: m
       */
      frontageWidth?: number | null;
      hasStorageRoom?: boolean | null;
      /**
       * Unit: m
       */
      ceilingHeight?: number | null;
    };
    medical?: {
      hasWaitingRoom?: boolean | null;
      medicalLicense?: string | null;
      numberOfExamRooms?: number | null;
    };
  };
  hospitality?: {
    totalRooms?: number | null;
    floors?: number | null;
    starRating?: ('1' | '2' | '3' | '4' | '5') | null;
    brand?: string | null;
    lastRenovationYear?: number | null;
    hasBeachAccess?: boolean | null;
    hotel?: {
      suites?: number | null;
      restaurants?: number | null;
      conferenceRooms?: number | null;
    };
    motel?: {
      parkingSpaces?: number | null;
      driveUpRooms?: boolean | null;
      isHighwayAccess?: boolean | null;
    };
    resort?: {
      suites?: number | null;
      hasPrivateBeach?: boolean | null;
      /**
       * Unit: m²
       */
      privateBeachArea?: number | null;
      hasGolfCourse?: boolean | null;
    };
    camp?: {
      tentCapacity?: number | null;
      hasShowers?: boolean | null;
      hasElectricity?: boolean | null;
    };
  };
  land?: {
    zoning?: ('residential' | 'commercial' | 'industrial' | 'agricultural' | 'mixed') | null;
    /**
     * Unit: m
     */
    roadWidth?: number | null;
    /**
     * Unit: m
     */
    frontageWidth?: number | null;
    hasUtilities?: boolean | null;
    allowedFloors?: number | null;
    /**
     * Unit: %
     */
    buildingRatio?: number | null;
    isCorner?: boolean | null;
    slope?: ('flat' | 'gentle' | 'moderate' | 'steep') | null;
    soilType?: string | null;
  };
  /**
   * Business metrics — updated regularly. Separate from property specifications.
   */
  operationalData?: {
    avgDailyRate?: number | null;
    occupancyRate?: number | null;
    revPAR?: number | null;
    lastReportDate?: string | null;
  };
  /**
   * Select the features for this property.
   */
  features?: (number | Feature)[] | null;
  /**
   * Additional specifications for rare/special cases. Not searchable.
   */
  customSpecifications?:
    | {
        label: string;
        /**
         * Optional Lucide icon name (e.g. Wind, Sun, Battery, Wifi)
         */
        icon?: string | null;
        valueType: 'text' | 'number' | 'date' | 'boolean' | 'url';
        value: string;
        id?: string | null;
      }[]
    | null;
  photos?: (number | Media)[] | null;
  /**
   * Paste a Google Maps URL (short/long), coordinates (lat,lng), or search address to auto-fill details.
   */
  mapsUrlInput?: string | null;
  location?: {
    geo?: {
      lat?: number | null;
      lng?: number | null;
    };
    address?: {
      street?: string | null;
      city?: string | null;
      state?: string | null;
      country?: string | null;
      zip?: string | null;
      /**
       * Auto-generated from components above.
       */
      fullAddress?: string | null;
    };
    search?: {
      citySlug?: string | null;
      stateSlug?: string | null;
      normalizedAddress?: string | null;
    };
    meta?: {
      source?: ('manual' | 'google_maps' | 'imported') | null;
      extractedAt?: string | null;
      extractionConfidence?: number | null;
    };
  };
  street?: string | null;
  location_legacy?: (number | null) | Location;
  hasProject?: boolean | null;
  projectImage?: (number | null) | Media;
  projectDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registered sellers/owners with properties listed
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sellers".
 */
export interface Seller {
  id: number;
  full_name: string;
  phone: string;
  company_name?: string | null;
  /**
   * Current verification status of the seller
   */
  verification_status: 'pending' | 'verified' | 'rejected';
  /**
   * Internal notes about this seller (only visible to admins)
   */
  notes?: string | null;
  /**
   * Total number of properties listed on the platform for this seller
   */
  properties_count?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'sellers';
}
/**
 * Incoming property listing requests from sellers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller-requests".
 */
export interface SellerRequest {
  id: number;
  propertyTypeSlug?: string | null;
  /**
   * Automatically derived from property type.
   */
  category?: ('residential' | 'commercial' | 'hospitality' | 'land') | null;
  property_type: number | PropertyType;
  property_title: string;
  property_description: string;
  property_location: string;
  city: string;
  state: string;
  country: string;
  asking_price: number;
  currency: 'EGP' | 'USD' | 'EUR';
  property_size?: number | null;
  latitude?: number | null;
  longitude?: number | null;
  google_maps_url?: string | null;
  constructionStatus: number | ConstructionStatus;
  residential?: {
    bedrooms?: number | null;
    bathrooms?: number | null;
    floor?: number | null;
    floors?: number | null;
    yearBuilt?: number | null;
    heatingType?: ('central' | 'electric' | 'gas' | 'oil' | 'propane') | null;
    villa?: {
      pools?: number | null;
      hasGarden?: boolean | null;
      hasGarage?: boolean | null;
      hasMajlis?: boolean | null;
      hasDriverRoom?: boolean | null;
      hasMaidRoom?: boolean | null;
    };
    apartment?: {
      hasBalcony?: boolean | null;
      hasMaidRoom?: boolean | null;
    };
    chalet?: {
      hasPool?: boolean | null;
      hasGarden?: boolean | null;
      isBeachfront?: boolean | null;
    };
  };
  commercial?: {
    floor?: number | null;
    parkingSpaces?: number | null;
    licenseType?: string | null;
    office?: {
      meetingRooms?: number | null;
      hasReception?: boolean | null;
      internetType?: ('fiber' | 'adsl' | 'none') | null;
      securityLevel?: ('24_7' | 'business_hours' | 'none') | null;
      elevators?: number | null;
    };
    restaurant?: {
      kitchenCount?: number | null;
      hasExhaust?: boolean | null;
      hasGasConnection?: boolean | null;
      outdoorSeatingCapacity?: number | null;
    };
    warehouse?: {
      loadingDocks?: number | null;
      /**
       * Unit: m
       */
      ceilingHeight?: number | null;
      hasTruckAccess?: boolean | null;
      fireSystem?: ('sprinkler' | 'extinguisher' | 'full' | 'none') | null;
    };
    factory?: {
      /**
       * Unit: kW
       */
      powerCapacityKW?: number | null;
      hazardZone?: ('none' | 'low' | 'medium' | 'high') | null;
      industrialLicense?: string | null;
    };
    retail?: {
      /**
       * Unit: m
       */
      frontageWidth?: number | null;
      hasStorageRoom?: boolean | null;
      /**
       * Unit: m
       */
      ceilingHeight?: number | null;
    };
    medical?: {
      hasWaitingRoom?: boolean | null;
      medicalLicense?: string | null;
      numberOfExamRooms?: number | null;
    };
  };
  hospitality?: {
    totalRooms?: number | null;
    floors?: number | null;
    starRating?: ('1' | '2' | '3' | '4' | '5') | null;
    brand?: string | null;
    lastRenovationYear?: number | null;
    hasBeachAccess?: boolean | null;
    hotel?: {
      suites?: number | null;
      restaurants?: number | null;
      conferenceRooms?: number | null;
    };
    motel?: {
      parkingSpaces?: number | null;
      driveUpRooms?: boolean | null;
      isHighwayAccess?: boolean | null;
    };
    resort?: {
      suites?: number | null;
      hasPrivateBeach?: boolean | null;
      /**
       * Unit: m²
       */
      privateBeachArea?: number | null;
      hasGolfCourse?: boolean | null;
    };
    camp?: {
      tentCapacity?: number | null;
      hasShowers?: boolean | null;
      hasElectricity?: boolean | null;
    };
  };
  land?: {
    zoning?: ('residential' | 'commercial' | 'industrial' | 'agricultural' | 'mixed') | null;
    /**
     * Unit: m
     */
    roadWidth?: number | null;
    /**
     * Unit: m
     */
    frontageWidth?: number | null;
    hasUtilities?: boolean | null;
    allowedFloors?: number | null;
    /**
     * Unit: %
     */
    buildingRatio?: number | null;
    isCorner?: boolean | null;
    slope?: ('flat' | 'gentle' | 'moderate' | 'steep') | null;
    soilType?: string | null;
  };
  /**
   * Select the features for this property request.
   */
  features?: (number | Feature)[] | null;
  /**
   * Registered name of the seller at submission time.
   */
  full_name: string;
  /**
   * Registered email address of the seller at submission time.
   */
  email: string;
  /**
   * Registered phone number of the seller at submission time.
   */
  phone: string;
  status: 'new' | 'reviewing' | 'approved' | 'rejected' | 'listed';
  referenceNumber?: string | null;
  /**
   * Auto-linked seller account record
   */
  seller?: (number | null) | Seller;
  /**
   * The live property document created from this request
   */
  publishedProperty?: (string | null) | Property;
  /**
   * Internal notes (not visible to seller)
   */
  admin_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types".
 */
export interface PropertyType {
  id: number;
  /**
   * Display name for this property type (e.g., Villa, Hotel, Resort).
   */
  name: string;
  /**
   * Select the main category for this property type.
   */
  category: number | PropertyCategory;
  /**
   * Select the specifications profile that applies to this property type.
   */
  specificationProfile:
    | 'villa'
    | 'apartment'
    | 'chalet'
    | 'office'
    | 'restaurant'
    | 'warehouse'
    | 'factory'
    | 'retail'
    | 'medical'
    | 'hotel'
    | 'motel'
    | 'resort'
    | 'camp'
    | 'land'
    | 'none';
  /**
   * URL-friendly identifier (lowercase, e.g., "villa", "elite-real-estate").
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-categories".
 */
export interface PropertyCategory {
  id: number;
  /**
   * Display name for this category (e.g., Residential, Commercial, Hospitality, Land).
   */
  name: string;
  /**
   * URL-friendly identifier.
   */
  slug: string;
  /**
   * Icon name from Lucide (e.g., Home, Building2, Hotel, Map).
   */
  icon?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-statuses".
 */
export interface ConstructionStatus {
  id: number;
  /**
   * Display name for this status in English (e.g., Ready to Move In, Under Construction).
   */
  name: string;
  /**
   * URL-friendly identifier (lowercase, e.g., "ready", "under-construction").
   */
  slug: string;
  /**
   * Visual color theme for badges in search cards and property detail views.
   */
  colorTheme: 'emerald' | 'amber' | 'blue' | 'indigo' | 'purple' | 'gray';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: number;
  /**
   * Name of the feature (e.g., "Hardwood Floors", "Swimming Pool")
   */
  name: string;
  /**
   * URL-friendly identifier.
   */
  slug: string;
  /**
   * Icon name from Lucide (e.g. Waves, Wifi, Car)
   */
  icon?: string | null;
  /**
   * Specify which property categories can use this feature. Leave empty for all.
   */
  visibleInCategories?: ('residential' | 'commercial' | 'hospitality' | 'land')[] | null;
  /**
   * Specify which property types can use this feature. Leave empty for all.
   */
  visibleInPropertyTypes?: (number | PropertyType)[] | null;
  /**
   * Categorization grouping for display in front-end.
   */
  featureGroup?: ('lifestyle' | 'security' | 'utilities' | 'amenities') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-statuses".
 */
export interface ListingStatus {
  id: number;
  /**
   * Display name for this status (e.g., Open Contract, Closed Contract, Draft).
   */
  name: string;
  /**
   * URL-friendly identifier (lowercase, e.g., "forsale", "sold", "draft").
   */
  slug: string;
  /**
   * Visual color theme for badges in the dashboard and property details.
   */
  colorTheme: 'emerald' | 'blue' | 'gray' | 'amber' | 'rose' | 'gold';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  formattedLocation?: string | null;
  zip: string;
  /**
   * City of the zip code
   */
  city: string;
  /**
   * State abbreviation of the zip code
   */
  state_abbr: string;
  /**
   * State name of the zip code
   */
  state_name: string;
  /**
   * County of the zip code
   */
  county?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Estimated population of the zip code
   */
  est_population?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers".
 */
export interface Buyer {
  id: number;
  full_name: string;
  company_name?: string | null;
  phone?: string | null;
  /**
   * Linked Google account identifier
   */
  google_id?: string | null;
  /**
   * Profile image from Google account
   */
  profile_image?: string | null;
  /**
   * Current verification status of the buyer
   */
  verification_status: 'pending' | 'submitted' | 'verified' | 'rejected';
  /**
   * Upload proof of financial capability (bank statement, investment portfolio, etc.)
   */
  proof_of_funds?: (number | null) | Media;
  /**
   * Internal notes about this buyer (only visible to admins)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'buyers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes".
 */
export interface VerificationCode {
  id: number;
  email: string;
  /**
   * 6-digit verification code
   */
  code: string;
  user_type: 'buyers' | 'sellers';
  expires_at: string;
  /**
   * Has this code been used to verify an account?
   */
  verified?: boolean | null;
  verified_at?: string | null;
  /**
   * Number of failed verification attempts
   */
  attempts?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * System-generated analytics log of unique property views. This collection is read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-views".
 */
export interface PropertyView {
  id: number;
  /**
   * The property that was viewed
   */
  property: string | Property;
  /**
   * The logged-in buyer or seller who viewed the property (optional)
   */
  user?:
    | ({
        relationTo: 'buyers';
        value: number | Buyer;
      } | null)
    | ({
        relationTo: 'sellers';
        value: number | Seller;
      } | null);
  /**
   * Unique identifier for the visitor (hashed fingerprint)
   */
  visitorId: string;
  /**
   * Session identifier for tracking multiple views in one session
   */
  sessionId?: string | null;
  viewedAt: string;
  /**
   * Browser user agent
   */
  userAgent?: string | null;
  /**
   * Visitor IP address (hashed for privacy)
   */
  ipAddress?: string | null;
  /**
   * Traffic source
   */
  source?: ('direct' | 'search' | 'social' | 'email' | 'referral' | 'other') | null;
  /**
   * Referrer URL
   */
  referrer?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  location?: {
    country?: string | null;
    city?: string | null;
    region?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  fullName: string;
  email: string;
  phone?: string | null;
  inquiryType: 'buyer' | 'property-owner' | 'general' | 'partnership' | 'support' | 'other';
  subject: string;
  message: string;
  /**
   * The property this inquiry is about (if applicable)
   */
  property?: (string | null) | Property;
  preferredContact?: ('email' | 'phone' | 'whatsapp') | null;
  buyingTimeline?: ('immediate' | '1_to_3_months' | '3_to_6_months' | '6_plus_months' | 'browsing') | null;
  budgetRange?: {
    min?: number | null;
    max?: number | null;
  };
  status: 'new' | 'in-progress' | 'resolved' | 'archived';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  /**
   * Assign this message to a team member
   */
  assignedTo?: (number | null) | User;
  /**
   * Internal notes for team (not visible to sender)
   */
  notes?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  doubleOptInConfirmed?: boolean | null;
  confirmedAt?: string | null;
  /**
   * Auto-generated double opt-in token
   */
  confirmationToken?: string | null;
  /**
   * Token expires after 24 hours
   */
  confirmationExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cached GeoIP locations for privacy-hashed IP addresses.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ip-locations".
 */
export interface IpLocation {
  id: number;
  hashedIp: string;
  country?: string | null;
  region?: string | null;
  city?: string | null;
  source?: string | null;
  lastUsed?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-folders';
        value: number | MediaFolder;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'properties';
        value: string | Property;
      } | null)
    | ({
        relationTo: 'features';
        value: number | Feature;
      } | null)
    | ({
        relationTo: 'buyers';
        value: number | Buyer;
      } | null)
    | ({
        relationTo: 'sellers';
        value: number | Seller;
      } | null)
    | ({
        relationTo: 'verification-codes';
        value: number | VerificationCode;
      } | null)
    | ({
        relationTo: 'property-views';
        value: number | PropertyView;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'seller-requests';
        value: number | SellerRequest;
      } | null)
    | ({
        relationTo: 'property-types';
        value: number | PropertyType;
      } | null)
    | ({
        relationTo: 'listing-statuses';
        value: number | ListingStatus;
      } | null)
    | ({
        relationTo: 'construction-statuses';
        value: number | ConstructionStatus;
      } | null)
    | ({
        relationTo: 'property-categories';
        value: number | PropertyCategory;
      } | null)
    | ({
        relationTo: 'ip-locations';
        value: number | IpLocation;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      }
    | {
        relationTo: 'sellers';
        value: number | Seller;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'buyers';
        value: number | Buyer;
      }
    | {
        relationTo: 'sellers';
        value: number | Seller;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  displayName?: T;
  storageKey?: T;
  alt?: T;
  folder?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  caption?: T;
  healthStatus?: T;
  originalFilename?: T;
  usedInBlogPosts?: T;
  usedInProperties?: T;
  usedInBuyers?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-folders_select".
 */
export interface MediaFoldersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  path?: T;
  depth?: T;
  sortOrder?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  formattedLocation?: T;
  zip?: T;
  city?: T;
  state_abbr?: T;
  state_name?: T;
  county?: T;
  latitude?: T;
  longitude?: T;
  est_population?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  id?: T;
  sortOrder?: T;
  seller?: T;
  seller_request?: T;
  views?: T;
  propertyTypeSlug?: T;
  title?: T;
  category?: T;
  propertyType?: T;
  listingStatus?: T;
  constructionStatus?: T;
  description?: T;
  price?: T;
  currency?: T;
  area?: T;
  basePriceInUSD?: T;
  residential?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        floor?: T;
        floors?: T;
        yearBuilt?: T;
        heatingType?: T;
        villa?:
          | T
          | {
              pools?: T;
              hasGarden?: T;
              hasGarage?: T;
              hasMajlis?: T;
              hasDriverRoom?: T;
              hasMaidRoom?: T;
            };
        apartment?:
          | T
          | {
              hasBalcony?: T;
              hasMaidRoom?: T;
            };
        chalet?:
          | T
          | {
              hasPool?: T;
              hasGarden?: T;
              isBeachfront?: T;
            };
      };
  commercial?:
    | T
    | {
        floor?: T;
        parkingSpaces?: T;
        licenseType?: T;
        office?:
          | T
          | {
              meetingRooms?: T;
              hasReception?: T;
              internetType?: T;
              securityLevel?: T;
              elevators?: T;
            };
        restaurant?:
          | T
          | {
              kitchenCount?: T;
              hasExhaust?: T;
              hasGasConnection?: T;
              outdoorSeatingCapacity?: T;
            };
        warehouse?:
          | T
          | {
              loadingDocks?: T;
              ceilingHeight?: T;
              hasTruckAccess?: T;
              fireSystem?: T;
            };
        factory?:
          | T
          | {
              powerCapacityKW?: T;
              hazardZone?: T;
              industrialLicense?: T;
            };
        retail?:
          | T
          | {
              frontageWidth?: T;
              hasStorageRoom?: T;
              ceilingHeight?: T;
            };
        medical?:
          | T
          | {
              hasWaitingRoom?: T;
              medicalLicense?: T;
              numberOfExamRooms?: T;
            };
      };
  hospitality?:
    | T
    | {
        totalRooms?: T;
        floors?: T;
        starRating?: T;
        brand?: T;
        lastRenovationYear?: T;
        hasBeachAccess?: T;
        hotel?:
          | T
          | {
              suites?: T;
              restaurants?: T;
              conferenceRooms?: T;
            };
        motel?:
          | T
          | {
              parkingSpaces?: T;
              driveUpRooms?: T;
              isHighwayAccess?: T;
            };
        resort?:
          | T
          | {
              suites?: T;
              hasPrivateBeach?: T;
              privateBeachArea?: T;
              hasGolfCourse?: T;
            };
        camp?:
          | T
          | {
              tentCapacity?: T;
              hasShowers?: T;
              hasElectricity?: T;
            };
      };
  land?:
    | T
    | {
        zoning?: T;
        roadWidth?: T;
        frontageWidth?: T;
        hasUtilities?: T;
        allowedFloors?: T;
        buildingRatio?: T;
        isCorner?: T;
        slope?: T;
        soilType?: T;
      };
  operationalData?:
    | T
    | {
        avgDailyRate?: T;
        occupancyRate?: T;
        revPAR?: T;
        lastReportDate?: T;
      };
  features?: T;
  customSpecifications?:
    | T
    | {
        label?: T;
        icon?: T;
        valueType?: T;
        value?: T;
        id?: T;
      };
  photos?: T;
  mapsUrlInput?: T;
  location?:
    | T
    | {
        geo?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
        address?:
          | T
          | {
              street?: T;
              city?: T;
              state?: T;
              country?: T;
              zip?: T;
              fullAddress?: T;
            };
        search?:
          | T
          | {
              citySlug?: T;
              stateSlug?: T;
              normalizedAddress?: T;
            };
        meta?:
          | T
          | {
              source?: T;
              extractedAt?: T;
              extractionConfidence?: T;
            };
      };
  street?: T;
  location_legacy?: T;
  hasProject?: T;
  projectImage?: T;
  projectDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  visibleInCategories?: T;
  visibleInPropertyTypes?: T;
  featureGroup?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyers_select".
 */
export interface BuyersSelect<T extends boolean = true> {
  full_name?: T;
  company_name?: T;
  phone?: T;
  google_id?: T;
  profile_image?: T;
  verification_status?: T;
  proof_of_funds?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sellers_select".
 */
export interface SellersSelect<T extends boolean = true> {
  full_name?: T;
  phone?: T;
  company_name?: T;
  verification_status?: T;
  notes?: T;
  properties_count?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verification-codes_select".
 */
export interface VerificationCodesSelect<T extends boolean = true> {
  email?: T;
  code?: T;
  user_type?: T;
  expires_at?: T;
  verified?: T;
  verified_at?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-views_select".
 */
export interface PropertyViewsSelect<T extends boolean = true> {
  property?: T;
  user?: T;
  visitorId?: T;
  sessionId?: T;
  viewedAt?: T;
  userAgent?: T;
  ipAddress?: T;
  source?: T;
  referrer?: T;
  device?: T;
  location?:
    | T
    | {
        country?: T;
        city?: T;
        region?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedDate?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  inquiryType?: T;
  subject?: T;
  message?: T;
  property?: T;
  preferredContact?: T;
  buyingTimeline?: T;
  budgetRange?:
    | T
    | {
        min?: T;
        max?: T;
      };
  status?: T;
  priority?: T;
  assignedTo?: T;
  notes?: T;
  ipAddress?: T;
  userAgent?: T;
  doubleOptInConfirmed?: T;
  confirmedAt?: T;
  confirmationToken?: T;
  confirmationExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seller-requests_select".
 */
export interface SellerRequestsSelect<T extends boolean = true> {
  propertyTypeSlug?: T;
  category?: T;
  property_type?: T;
  property_title?: T;
  property_description?: T;
  property_location?: T;
  city?: T;
  state?: T;
  country?: T;
  asking_price?: T;
  currency?: T;
  property_size?: T;
  latitude?: T;
  longitude?: T;
  google_maps_url?: T;
  constructionStatus?: T;
  residential?:
    | T
    | {
        bedrooms?: T;
        bathrooms?: T;
        floor?: T;
        floors?: T;
        yearBuilt?: T;
        heatingType?: T;
        villa?:
          | T
          | {
              pools?: T;
              hasGarden?: T;
              hasGarage?: T;
              hasMajlis?: T;
              hasDriverRoom?: T;
              hasMaidRoom?: T;
            };
        apartment?:
          | T
          | {
              hasBalcony?: T;
              hasMaidRoom?: T;
            };
        chalet?:
          | T
          | {
              hasPool?: T;
              hasGarden?: T;
              isBeachfront?: T;
            };
      };
  commercial?:
    | T
    | {
        floor?: T;
        parkingSpaces?: T;
        licenseType?: T;
        office?:
          | T
          | {
              meetingRooms?: T;
              hasReception?: T;
              internetType?: T;
              securityLevel?: T;
              elevators?: T;
            };
        restaurant?:
          | T
          | {
              kitchenCount?: T;
              hasExhaust?: T;
              hasGasConnection?: T;
              outdoorSeatingCapacity?: T;
            };
        warehouse?:
          | T
          | {
              loadingDocks?: T;
              ceilingHeight?: T;
              hasTruckAccess?: T;
              fireSystem?: T;
            };
        factory?:
          | T
          | {
              powerCapacityKW?: T;
              hazardZone?: T;
              industrialLicense?: T;
            };
        retail?:
          | T
          | {
              frontageWidth?: T;
              hasStorageRoom?: T;
              ceilingHeight?: T;
            };
        medical?:
          | T
          | {
              hasWaitingRoom?: T;
              medicalLicense?: T;
              numberOfExamRooms?: T;
            };
      };
  hospitality?:
    | T
    | {
        totalRooms?: T;
        floors?: T;
        starRating?: T;
        brand?: T;
        lastRenovationYear?: T;
        hasBeachAccess?: T;
        hotel?:
          | T
          | {
              suites?: T;
              restaurants?: T;
              conferenceRooms?: T;
            };
        motel?:
          | T
          | {
              parkingSpaces?: T;
              driveUpRooms?: T;
              isHighwayAccess?: T;
            };
        resort?:
          | T
          | {
              suites?: T;
              hasPrivateBeach?: T;
              privateBeachArea?: T;
              hasGolfCourse?: T;
            };
        camp?:
          | T
          | {
              tentCapacity?: T;
              hasShowers?: T;
              hasElectricity?: T;
            };
      };
  land?:
    | T
    | {
        zoning?: T;
        roadWidth?: T;
        frontageWidth?: T;
        hasUtilities?: T;
        allowedFloors?: T;
        buildingRatio?: T;
        isCorner?: T;
        slope?: T;
        soilType?: T;
      };
  features?: T;
  full_name?: T;
  email?: T;
  phone?: T;
  status?: T;
  referenceNumber?: T;
  seller?: T;
  publishedProperty?: T;
  admin_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-types_select".
 */
export interface PropertyTypesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  specificationProfile?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-statuses_select".
 */
export interface ListingStatusesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  colorTheme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "construction-statuses_select".
 */
export interface ConstructionStatusesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  colorTheme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "property-categories_select".
 */
export interface PropertyCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ip-locations_select".
 */
export interface IpLocationsSelect<T extends boolean = true> {
  hashedIp?: T;
  country?: T;
  region?: T;
  city?: T;
  source?: T;
  lastUsed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  companyName: string;
  companyLogo?: (number | null) | Media;
  partner?: {
    /**
     * Turn this on to show the partner integration (badge, visualization button, and design tab) across all eligible property pages.
     */
    isActive?: boolean | null;
    /**
     * e.g. Itqan
     */
    name?: string | null;
    /**
     * e.g. https://itcansolution.com/
     */
    websiteUrl?: string | null;
    logo?: (number | null) | Media;
    /**
     * Short promotional text to show next to the logo. e.g. "Imagine your home with".
     */
    badgeText?: string | null;
  };
  contactEmail: string;
  contactPhone: string;
  contactOffice: string;
  businessHours: {
    mondayFriday: string;
    saturday: string;
    sunday: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle: string;
  heroDescription: string;
  visionTitle: string;
  visionText: string;
  missionText: string;
  visionImage?: (number | null) | Media;
  values: {
    title: string;
    description: string;
    id?: string | null;
  }[];
  strengthsTitle: string;
  strengths: {
    strength: string;
    id?: string | null;
  }[];
  keysOfSuccess: {
    key: string;
    id?: string | null;
  }[];
  strengthsImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  companyName?: T;
  companyLogo?: T;
  partner?:
    | T
    | {
        isActive?: T;
        name?: T;
        websiteUrl?: T;
        logo?: T;
        badgeText?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  contactOffice?: T;
  businessHours?:
    | T
    | {
        mondayFriday?: T;
        saturday?: T;
        sunday?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  visionTitle?: T;
  visionText?: T;
  missionText?: T;
  visionImage?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  strengthsTitle?: T;
  strengths?:
    | T
    | {
        strength?: T;
        id?: T;
      };
  keysOfSuccess?:
    | T
    | {
        key?: T;
        id?: T;
      };
  strengthsImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}